# NOTE: This file name MUST be .markdownlint.yaml
#
# See more rules (copypasta) at:
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# ---

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013: false

# MD024/no-duplicate-heading : Multiple headings with the same content : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md024.md
MD024:
  # Only check sibling headings
  siblings_only: false
