--[[
Disabled: LazyVim stuff I don't want.
]]
return {
  -- Enabled (kept for easy copy/paste to disable below)
  --{ "bufferline.nvim", enabled = false },
  --{ "cmp-buffer", enabled = false },
  --{ "cmp-nvim-lsp", enabled = false },
  --{ "cmp-path", enabled = false },
  --{ "cmp_luasnip", enabled = false },
  --{ "copilot-cmp", enabled = false },
  --{ "copilot.lua", enabled = false },
  --{ "friendly-snippets", enabled = false },
  --{ "lazy.nvim", enabled = false },
  --{ "lazygit.nvim", enabled = false },
  --{ "LazyVim", enabled = false },
  --{ "lualine.nvim", enabled = false },
  --{ "LuaSnip", enabled = false },
  --{ "mason-lspconfig.nvim", enabled = false },
  --{ "mason.nvim", enabled = false },
  --{ "mini.bufremove", enabled = false },
  --{ "mini.comment", enabled = false },
  --{ "mini.indentscope", enabled = false },
  --{ "mini.pairs", enabled = false },
  --{ "mini.surround", enabled = false },
  --{ "neo-tree.nvim", enabled = false },
  --{ "neoconf.nvim", enabled = false },
  --{ "neodev.nvim", enabled = false },
  --{ "noice.nvim", enabled = false },
  --{ "none-ls.nvim", enabled = false },
  --{ "nui.nvim", enabled = false },
  --{ "nvim-cmp", enabled = false },
  --{ "nvim-colorizer.lua", enabled = false },
  --{ "nvim-lspconfig", enabled = false },
  --{ "nvim-notify", enabled = false },
  --{ "nvim-treesitter", enabled = false },
  --{ "nvim-treesitter-context", enabled = false },
  --{ "nvim-treesitter-textobjects", enabled = false },
  --{ "nvim-web-devicons", enabled = false },
  --{ "plenary.nvim", enabled = false },
  --{ "telescope-fzf-native.nvim", enabled = false },
  --{ "telescope.nvim", enabled = false },
  --{ "todo-comments.nvim", enabled = false },
  --{ "tokyonight.nvim", enabled = false },
  --{ "vim-illuminate", enabled = false },
  --{ "vim-startuptime", enabled = false },
  --{ "which-key.nvim", enabled = false },

  -- Disabled
  { "catppuccin", enabled = false },
  { "conform.nvim", enabled = false },
  { "dressing.nvim", enabled = false },
  { "flash.nvim", enabled = false },
  { "gitsigns.nvim", enabled = false },
  { "indent-blankline.nvim", enabled = false },
  { "mini.ai", enabled = false },
  { "nvim-lint", enabled = false },
  { "nvim-spectre", enabled = false },
  { "nvim-ts-autotag", enabled = false },
  { "nvim-ts-context-commentstring", enabled = false },
  { "persistence.nvim", enabled = false },
  { "trouble.nvim", enabled = false },
}
