# Recipe targets (that aren't files...all of them)
.PHONY : default dev development


# Recipes: Default (first is "default")
default: development


# Recipes: Aliases
dev: development


development:
	echo "Sup"
